main:
  steps:
    - example-gen1:
      call: http.post
      args:
        url: https://us-west1-jeffreyhung-test.cloudfunctions.net/example-gen1
        auth:
          type: OIDC
          audience: https://us-west1-jeffreyhung-test.cloudfunctions.net/example-gen1
          
