name: "Terraform/Terragrunt Apply"

on:
  push:
    branches:
    - main

env:
  TF_VERSION: '1.7.5'
  TG_VERSION: '0.59.5'
  TG_DIR: '.'

jobs:
  terraform:
    name: 'Terraform'
    runs-on: ubuntu-latest
    defaults:
     run:
       shell: bash
    permissions:
     contents: 'read'
     id-token: 'write'
     pull-requests: 'write'

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - id: 'auth'
      name: 'Authenticate to Google Cloud'
      uses: 'google-github-actions/auth@v1'
      with:
        workload_identity_provider: 'projects/546928617664/locations/global/workloadIdentityPools/gha-terraform-checker-pool/providers/gha-terraform-checker-provider'
        service_account: 'gha-cloud-functions-deployment@jeffreyhung-test.iam.gserviceaccount.com'

    - name: apply
      uses: gruntwork-io/terragrunt-action@v2
      id: apply
      with:
        tf_version: ${{ env.TF_VERSION }}
        tg_version: ${{ env.TG_VERSION }}
        tg_dir: ${{ env.TG_DIR }}
        tg_command: 'run-all apply'