name: Terraform Plan

on:
  pull_request:
    branches:
      - main

jobs:
  build:
    name: tf plan
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write
      pull-requests: write

    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683

      - name: gcp auth (tf plan)
        id: auth
        uses: google-github-actions/auth@ba79af03959ebeac9769e648f473a284504d9193
        with:
          workload_identity_provider: projects/546928617664/locations/global/workloadIdentityPools/gha-terraform-checker-pool/providers/gha-terraform-checker-provider
          service_account: gha-cloud-functions-deployment@jeffreyhung-test.iam.gserviceaccount.com

      - name: terraform plan
        id: terraform-plan
        uses: dflook/terraform-plan@2c1e6cc4d10cb56cf366d99b01fbf15307df65b5 # v1.48.0
        if:
          ${{ steps.auth.outcome == 'success'}}
        with:
          add_github_comment: changes-only
        env:
            GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
